### PR TITLE
Added Three Solutions in python

### PR DESCRIPTION
**Pull request by sumanth-botlagunta**
@anishLearnsToCode  I have added solutions to the following questions in python:

- [208: implement Trie (Prefix Tree)](https://github.com/anishLearnsToCode/leetcode-algorithms/commit/49903da3213d49566e4cb7b69f4214d8ca1951ab)
- [2348: Number of Zero-Filled Subarrays](https://github.com/anishLearnsToCode/leetcode-algorithms/commit/89a75cf0be6e768ddfa437c043268d76b4334840)
- [218: The Skyline Problem](https://github.com/anishLearnsToCode/leetcode-algorithms/commit/4bbca0152bc68de335bc6414d3fc5049e88b0cde)

### CODE REVIEW

**Comment by anishLearnsToCode** [comment]
Thanks a lot for the 3 solutions !! I have tested them and they are all passing. Just one thing before I merge them. Can you also add the link to the correspondibg leetcode problem on each of the 3 solutions !

like:

```py
// https://leetcode.com/problems/two-sum/
// T: O(N)
// S: O(N)

your code here
```  

and also please add the time + space complexity for each of the 3 problems that you have solved. 

Thanks again for your contributions 😸

**Comment by sumanth-botlagunta** [comment]
@anishLearnsToCode 
I have added the link to the corresponding leetCode problem on each of the solutions and also added the time + space complexity 
[added Links + Time & Space Complexity](https://github.com/anishLearnsToCode/leetcode-algorithms/pull/10/commits/98fc01f2c1b55b2c2e9bee58657f6214994e2945)

**Comment by anishLearnsToCode** [comment]
Thank you very much ! 🥳

**Comment by anishLearnsToCode** [comment]
I have merged your pull request and  i would highly appreciate any more contributions from you as well, I would just like to say one thing that in the future create 1 pr per problem, so if you have solved 3 problems then create 3 prs for each solution. 

Also for every pr, you can keep the title as:

solves {problem name} (#1234 --> leetcode number) in python

**Pull request merged**
